=== opticyclic/fast-code/resources/fast-code-rules.xsd
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://fast-code.sourceforge.net/xsd/fast-code-rules.xsd" targetNamespace="http://fast-code.sourceforge.net/xsd/fast-code-rules.xsd"  elementFormDefault="qualified">
<!-- xmlns="http://fast-code.sourceforge.net"
    targetNamespace="http://fast-code.sourceforge.net" -->
    <xs:element name="actions">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="properties" name="properties" maxOccurs="1" minOccurs="0"/>
                <!--
				<xs:element name="rules">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="rule" name="rule" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				 -->
                <xs:element name="action" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="properties" name="properties" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="action-ref" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
			                            <xs:element name="parameters" minOccurs="0">
			                                <xs:complexType>
			                                    <xs:sequence>
			                                        <xs:element name="parameter" minOccurs="1" maxOccurs="unbounded">
			                                        	<xs:complexType>
			                                        		<xs:sequence>
																<xs:element name="options" type="options" maxOccurs="1" minOccurs="0"/>
															</xs:sequence>
			                                        		<xs:attribute name="name" type="xs:string" use="required"/>
			                                        		<xs:attribute name="value" type="xs:string"/>
			                                        	</xs:complexType>
			                                        </xs:element>
			                                    </xs:sequence>
			                                </xs:complexType>
			                            </xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"/>
									<!--  Name of the previously defined action to be invoked-->
									<xs:attribute name="action-name" type="xs:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="rules" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="rule" name="rule" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="type" type="xs:string"/>
                	</xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="rule">
        <xs:sequence>
            <xs:element name="rule-actions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="rule-action" minOccurs="1"  maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element type="properties" name="properties" maxOccurs="1" minOccurs="0"/>
                                    <xs:element type="select" name="select" maxOccurs="unbounded" minOccurs="0"/>
                                    <!-- source code to be used in the action-->
                                    <xs:element name="source" type="xs:string" minOccurs="0"/>
                                </xs:sequence>
                                <!-- type is type of action, can be create update open snippet import etc-->
                                <xs:attribute name="action-type" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="prompt"/>
                                            <xs:enumeration value="create"/>
                                            <xs:enumeration value="import"/>
                                            <xs:enumeration value="select"/>
                                            <xs:enumeration value="update"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <!-- entity can be class interface file folder method etc-->
                                <xs:attribute name="action-entity">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="class"/>
                                            <xs:enumeration value="field"/>
                                            <xs:enumeration value="interface"/>
                                            <xs:enumeration value="snippet"/>
                                            <xs:enumeration value="method"/>
                                            <xs:enumeration value="file"/>
                                            <xs:enumeration value="folder"/>
                                            <xs:enumeration value="package"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <!-- target can be blank or name of another class, interface, file, folder,
                                   field, method, etc.
                                -->
                                <xs:attribute name="target"/>
                                <!-- result is the place holder for the entity that was created/updated
                                    This can be used in subsequent actions as ${result}
                                    //target shud be method name or FQ class name
                                -->
                                <xs:attribute name="result"/>
                                <!-- Input is the item to use for the action. E.g for import action input
                                    will be the field/class one has created earlier.
                                -->
                                <xs:attribute name="input"/>
                                <!-- Name is the name of the entity to to be created in this action. E.g for create action name
                                    will ${name}DAO, where {name} can be the result of a prompt action.
                                -->
                                <xs:attribute name="name"/>
                                <!-- the working java project name.
                                -->
                                <xs:attribute name="project"/>
                                <!-- package where class or interface or file or folder needs to be created.
                                -->
                                <xs:attribute name="package"/>
                                <!-- project source path.
                                -->
                                <xs:attribute name="src_path"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="name" use="required"/>
                    <xs:attribute name="ref"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="select">
            <xs:sequence>
                <xs:element name="value">
                    <xs:complexType>
                    	<xs:simpleContent>
	                    	<xs:extension base="xs:string">
	                    		<xs:attribute name="restriction">
	                               <xs:simpleType>
	                                   <xs:restriction base="xs:string">
	                                       <xs:enumeration value="subclassOf"/>
	                                       <xs:enumeration value="implementationOf"/>
	                                       <xs:enumeration value="containedIn"/>
	                                   </xs:restriction>
	                               </xs:simpleType>
	                           </xs:attribute>
	                    	</xs:extension>
                    	</xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="value"/>
            <xs:attribute name="selection-message" use="required"/>
            <xs:attribute name="selection-count" default="multiple">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="single"/>
                        <xs:enumeration value="multiple"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="optional" default="false">
                <xs:simpleType>
                    <xs:restriction base="xs:boolean">
                        <xs:pattern value="false"/>
                        <xs:pattern value="true"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="class"/>
                        <xs:enumeration value="interface"/>
                        <xs:enumeration value="file"/>
                        <xs:enumeration value="folder"/>
                        <xs:enumeration value="field"/>
                        <xs:enumeration value="method"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
    </xs:complexType>

    <xs:complexType name="properties">
        <xs:sequence>
            <xs:element name="property" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                	<xs:sequence>
                		<xs:element name="options" type="options" maxOccurs="1" minOccurs="0"/>
                	</xs:sequence>
                    <xs:attribute name="name" use="required"/>
                    <xs:attribute name="value"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


	<xs:complexType name="options">
		<xs:sequence>
			<xs:element name="option" minOccurs="2" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="choice" default="single">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="single"/>
					<xs:enumeration value="multiple"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

</xs:schema>

=== opticyclic/fast-code/resources/fast-code-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://fast-code.sourceforge.net/xsd/fast-code-rules.xsd"> <!-- xsi:noNamespaceSchemaLocation="fast-code-rules.xsd" xmlns="http://fast-code.sourceforge.net"> xsi:noNamespaceSchemaLocation="fast-code-rules.xsd" 
		> -->
	<!-- xsi:schemaLocation="http://fast-code.sourceforge.net/xsd/fast-code-rules.xsd"> > -->
	<action name="PROMPT" type="abstract">
		<rules>
			<rule>
				<rule-actions name="Get Name from User">
					<rule-action action-type="prompt" result="name"></rule-action>
				</rule-actions>
			</rule>
		</rules>
	</action>
	<action name="SELECT_CLASS" type="abstract">
		<rules>
			<rule>
				<rule-actions name="select a class">
					<rule-action action-type="select" action-entity="class" result="class"></rule-action>
				</rule-actions>
			</rule>
		</rules>
	</action>
	<action name="CREATE_CLASS" type="abstract">
		<rules>
			<rule>
				<rule-actions name="create class">
					<!-- <rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Class Name"></property></properties>
					</rule-action> -->
					<rule-action action-type="create" action-entity="class" name="${name}${suffix}" project="TestFC" package="com.example" result="class">
						<source>public class ${name}${suffix} {\n}</source>
					</rule-action>
					<rule-action ></rule-action>
					
				</rule-actions>
			</rule>
		</rules>
	</action>
	<!-- <action name="COPY">  take the file in the editor - take the jsp pattern and create a new file with the pattern in the source , with the new name
		<file-patter>*Impl.java</file-patter>
		<source>public class ${name}${suffix} {\n}</source>
		suffix = Impl
	</action>
	<action name="COPY">
		<file-patter>*.jsp</file-patter>
		<source>public class ${name}${suffix} {\n}</source>
	</action> -->
	<action name="CREATE_FIELD" type="abstract">
		<!-- <action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Field Name"></parameter>
			</parameters>
		</action-ref>
		<action-ref action-name="SELECT">
			<parameters>
				<parameter name="action-entity" value="class"></parameter>
				<parameter name="result" value="fieldType"></parameter>
			</parameters>
		</action-ref> -->
		<properties>
			<property name="targetClass" value="com.example.common.Constants"></property>
		</properties>
		<rules>
			<rule>
				<rule-actions name="create field">
					<!-- <rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Field Name"></property></properties>
					</rule-action> -->
					<rule-action action-type="select" action-entity="class" result="fieldType"></rule-action>
					<rule-action action-type="create" action-entity="field" target="${targetClass}" project="TestFC" input="${fieldType}" result="field">
						<source>public ${fieldType.name} ${name}; </source> <!-- to do -->
					</rule-action>
					<rule-action action-type="import" input="${fieldType}" target="${targetClass}"></rule-action>
				</rule-actions>
			</rule>
		</rules>

	</action>
	<action name="CREATE_FIELD_SNIPPET">
		<action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Field Name"></parameter> <!-- get method source add to it, delete and create method... ... -->
			</parameters>
		</action-ref>
		<!-- <rules>
			<rule>
				<rule-actions name="">
					<rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Field Name"></property></properties>
					</rule-action></rule-actions></rule>
		</rules> -->
		<action-ref action-name="CREATE_FIELD" name="Field">
			<parameters>
				<parameter name="targetClass" value="com.example.Student#meth1"></parameter>
				<parameter name="snippet" value="true"></parameter>
				<parameter name="source" value="${fieldType.name} ${name};"></parameter>
			</parameters>
		</action-ref>
	</action>
	<action name="CREATE_STATIC_FIELD">
		<action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Static Field Name"></parameter>
			</parameters>
		</action-ref>
		<action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Static Field Value"></parameter>
				<parameter name="result" value="value"></parameter>
			</parameters>
		</action-ref>
		<!-- <rules>
			<rule>
				<rule-actions name="">
					<rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Field Name"></property></properties>
					</rule-action></rule-actions></rule>
		</rules> -->
		<action-ref action-name="CREATE_FIELD" name="Field">
			<parameters>
				<parameter name="targetClass" value="com.example.Student"></parameter>
				<parameter name="source" value="public static ${fieldType.name} ${name} = ${value}; "></parameter>
				
			</parameters>
		</action-ref>
		<rules>
			<rule>
				<rule-actions>
					<rule-action action-type="import"  input="${targetClass}" target="com.MyClass" >
						<properties><property name="staticImport" value="true"></property></properties>
					</rule-action>
					<rule-action action-type="create" action-entity="snippet">
						<source>${name}</source>
					</rule-action>
				</rule-actions>
			</rule>
		</rules>
	</action>
	<action name="CREATE_PREFERENCE_FIELD">
		<action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Field Name"></parameter>
			</parameters>
		</action-ref>
		<action-ref action-name="CREATE_FIELD" name="Field">
			<parameters>
				<parameter name="targetClass" value="com.example.RuleClass1"></parameter>
				<parameter name="source" value="public ${fieldType.name} ${name}; "></parameter>
				<!-- <parameter name="restriction" value="subClassOf"></parameter>
				<parameter name="subClassOf" value="comm.Person"></parameter> -->
			</parameters>
		</action-ref>
		<action-ref action-name="SELECT_CLASS" >
			<parameters>
				<parameter name="restriction" value="subClassOf"></parameter>
				<parameter name="subClassOf" value="${fieldType.fullyQualifiedName}"></parameter>
				
			</parameters>
		</action-ref>
		<rules>
			<rule>
				<rule-actions name="">
					<rule-action action-entity="snippet" action-type="create" input="${field}">
						<source>this.${field.name} = new ${class.name} ();</source> 
					</rule-action>
					<rule-action action-type="import" input="${class}" target="${targetClass}"></rule-action>
				</rule-actions>
			</rule>
		</rules>
		
	</action>
<!-- 	<action name="Create Field and Instance IN ANOTHER CLASS"> to do
		<action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Field Name"></parameter>
			</parameters>
		</action-ref>
		<action-ref action-name="SELECT"><parameters><parameter name="result" value="fieldType"></parameter></parameters></action-ref>
		<action-ref action-name="CREATE_FIELD" name="Field">
			<parameters>
				<parameter name="target" value="com.example.common.Constants"></parameter>
			</parameters>
		</action-ref>
		<action-ref action-name="CREATE_FIELD" name="Field">
			<parameters>
				<parameter name="target" value="com.example.Student#meth1"></parameter>
				<parameter name="snippet" value="true"></parameter>
				<parameter name="source" value="this.${field.name} = new ${field.type}();"></parameter>
			</parameters>
		</action-ref>
		
		<rules>
			<rule>
				<rule-actions name="import">
					<rule-action action-type="import" input="${fieldType}" target="com.example.Student"></rule-action>
				</rule-actions>
			</rule>
		</rules>
	</action> -->
	<action name="CREATE_INTERFACE" type="abstract">
		<!-- <action-ref  action-name="PROMPT" name="">
			<parameters>
				<parameter name="title" value="Enter Interface Name"></parameter>
			</parameters>
		</action-ref> -->
		<rules>
			<rule>
				<rule-actions name="create interface">
					<rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Field Name"></property></properties>
					</rule-action>
					<rule-action action-type="create" action-entity="interface" input="${name}" result="interface" name="${name}${suffix}">
						<source>public interface ${name}${suffix} {\n}</source>
					</rule-action>
				</rule-actions>
			</rule> 
		</rules>
	</action>
	<action name="CREATE_INTERFACE_AND_IMPLEMENTATION" type="abstract">
		<!-- <action-ref action-name="PROMPT">
			<parameters>
				<parameter name="title" value="Enter Interface Name"></parameter>
			</parameters>
		</action-ref> -->
		<rules>
			<rule>
				<rule-actions name="create interface and implementation">
					<!-- <rule-action action-type="prompt" result="name">
						<properties><property name="title" value="Enter Field Name"></property></properties>
					</rule-action> -->
					<rule-action action-type="create" action-entity="interface" input="${name}" result="interface" name="${name}${suffix}">
						<source>public interface ${name}${suffix} {\n}</source>
					</rule-action>
					<rule-action action-type="create" action-entity="class" input="${interface}" name="${interface.name}Impl" project="TestFC" result="class">
						<properties>
							<property name="implSubPckage" value="impl"></property>
							
						</properties>
						<source>public class ${interface.name}Impl implements ${interface.name}	{\n}</source>  
					</rule-action>
					<rule-action action-type="import" input="${interface}" target="${class}"></rule-action>
					<!-- <rule-action action-type="create" action-entity="field" target="${class}" result="field"><source>${interface.name} ${interface.name.toLowerCase()};</source></rule-action> -->
				</rule-actions>
			</rule>
		</rules>
	</action>
	<action name="CREATE_SIMILAR_CLASSES" > <!-- result="" -->
		<properties>
			<property name="basePackage" value="com.example"></property>
		</properties>
		<!-- <rules>
			<rule>
				<rule-actions name="">
					<rule-action action-type="prompt" result="name">
